package com.piq.erstieNavi;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.preference.ListPreference;
import android.preference.Preference;
import android.preference.Preference.OnPreferenceChangeListener;
import android.preference.PreferenceActivity;
import android.preference.PreferenceManager;
import android.widget.Toast;

/**
 * This is the activity for feature 1 in the dashboard application. It displays some text and provides a way to get back to the home activity.
 */

public class SettingsActivity extends PreferenceActivity {

	/**
	 * onCreate Called when the activity is first created. This is where you should do all of your normal static set up: create views, bind data to lists, etc. This method also provides you with a
	 * Bundle containing the activity's previously frozen state, if there was one. Always followed by onStart().
	 * 
	 * @param savedInstanceState
	 *            Bundle
	 */

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		addPreferencesFromResource(R.layout.activity_settings);
		ListPreference ll = (ListPreference) findPreference("locationizeMethod");
		ll.setOnPreferenceChangeListener(onSelectItem);
	}

	@Override
	protected void onPause() {
		save();
		super.onPause();
	}

	@Override
	protected void onDestroy() {
		save();
		super.onDestroy();
	}

	private void save(String method) {
		SharedPreferences pref = PreferenceManager.getDefaultSharedPreferences(this);
		pref.edit().putString("locationizeMethod", method).commit();
	}

	private void save() {
		String locationizeMethod = "";
		ListPreference ll = (ListPreference) findPreference("locationizeMethod");
		locationizeMethod = ll.getValue();
		SharedPreferences pref = PreferenceManager.getDefaultSharedPreferences(this);
		pref.edit().putString("locationizeMethod", locationizeMethod).commit();
	}

	public void toastL(String msg) {
		Toast.makeText(getApplicationContext(), msg, Toast.LENGTH_LONG).show();
	} // end toast

	public OnPreferenceChangeListener onSelectItem = new OnPreferenceChangeListener() {

		public boolean onPreferenceChange(Preference arg0, Object value) {
			String locationizeMethod = (String) value;
			save(locationizeMethod);

			if (locationizeMethod.equals("gps")) {
				toastL("gps –> (GPS, AGPS): Name of the GPS location provider. This provider determines location using satellites. Depending on conditions, this provider may take a while to return a location fix.");
				toastL("Accuracy: 20ft ... Powerusage: High");
			}
			if (locationizeMethod.equals("network")) {
				toastL("network –> (AGPS, CellID, WiFi MACID): Name of the network location provider. This provider determines location based on availability of cell tower and WiFi access points. Results are retrieved by means of a network lookup.");
				toastL("Accuracy: 200ft ... Powerusage: Middle");
			}
			if (locationizeMethod.equals("passive")) {
				toastL("passive –> (CellID, WiFi MACID): A special location provider for receiving locations without actually initiating a location fix. This provider can be used to passively receive location updates when other applications or services request them without actually requesting the locations yourself. This provider will return locations generated by other providers.");
				toastL("Accuracy: 5300ft/1Mile ... Powerusage: Low");
			}

			return true;
		}
	};

} // end class
